language: php
php:
  - "8.0"
install: composer install --dev
script:
  - php vendor/atoum/atoum/bin/atoum --no-code-coverage -d sources/tests/Unit/ -af vendor/autoload.php
  - ./vendor/bin/phpcs --standard=psr2 --runtime-set ignore_warnings_on_exit true --report=summary sources

